FROM mcr.microsoft.com/dotnet/aspnet:6.0 AS base
WORKDIR /app

FROM mcr.microsoft.com/dotnet/sdk:6.0 AS build
WORKDIR /src
COPY ["JobConsole/JobConsole.csproj", "JobConsole/"]
RUN dotnet restore "JobConsole/JobConsole.csproj"
COPY . .
WORKDIR "/src/JobConsole"
RUN dotnet build "JobConsole.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "JobConsole.csproj" -c Release -o /app/publish

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "JobConsole.dll"]